package com.carhub.domain;

public enum RequestStatus {
    DRAFT,
    REQUEST_SUBMITTED,
    UNDER_REVIEW,
    CLARIFICATION_REQUESTED,
    APPROVED_BY_COMPANY,
    REJECTED_BY_COMPANY,
    PAYMENT_PENDING,
    FORWARDED_TO_PROVIDER,
    ACCEPTED_BY_PROVIDER,
    IN_PROGRESS,
    SUPPORT_ESCALATION,
    COMPLETED,
    CANCELLED,
    RESCHEDULED,
    REFUND_INITIATED,
    REFUND_COMPLETED
}
