-- Add region, route order, total distance, and sub-places to support curated local tourism packages
ALTER TABLE travel_package
    ADD COLUMN IF NOT EXISTS region VARCHAR(20),
    ADD COLUMN IF NOT EXISTS route_order TEXT,
    ADD COLUMN IF NOT EXISTS total_distance_km INT,
    ADD COLUMN IF NOT EXISTS sub_places TEXT;

CREATE INDEX IF NOT EXISTS idx_travel_package_region
    ON travel_package(region, availability_status);

-- Seed 10 curated Pune/Nashik/Shirdi tourism packages (admin-managed, no provider)
INSERT INTO travel_package (
    id, slug, title, destination, category, summary, description,
    starting_price, currency, duration_days, availability_status, featured,
    region, route_order, total_distance_km, sub_places, car_type, distance_km,
    image_url, pickup_availability_mode, created_at, updated_at
) VALUES

-- Route 1: Pune Heritage Circuit
(gen_random_uuid(),
 'pune-heritage-circuit',
 'Pune Heritage Circuit',
 'Sinhagad Fort',
 'Heritage',
 'Visit Parvati Hill, Shaniwar Wada, Dagdusheth Ganpati, Saras Baug, Sinhagad Fort and Khadakwasla Dam in a single day.',
 'A full-day heritage circuit covering Pune''s most iconic historical and spiritual landmarks. Includes sightseeing at Parvati Hill, the historic Shaniwar Wada, Dagdusheth Halwai Ganpati temple, Saras Baug gardens, trekking at Sinhagad Fort and a scenic sunset at Khadakwasla Dam.',
 1815.00, 'INR', 1, 'AVAILABLE', true,
 'Pune',
 'Pune → Parvati Hill (7AM) → Shaniwar Wada (8:30AM) → Dagdusheth Ganpati (9:30AM) → Saras Baug (10:15AM) → Sinhagad Fort (11:30AM-lunch) → Khadakwasla Dam (4:30PM-sunset) → Pune (6:30PM)',
 85,
 'Parvati Hill,Shaniwar Wada,Dagdusheth Halwai Ganpati,Saras Baug,Khadakwasla Dam',
 'FOUR_SEATER', 85.0,
 'https://images.unsplash.com/photo-1582502695531-158869811fcc?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 2: Pune Dam & Ghat Circuit
(gen_random_uuid(),
 'pune-dam-ghat-circuit',
 'Pune Dam & Ghat Circuit',
 'Mulshi Dam',
 'Nature',
 'Scenic day trip through Pashan Lake, Mulshi Dam, Tamhini Ghat, Andharban View Point and Pawna Lake.',
 'A nature lover''s circuit through the most scenic dams, ghats and viewpoints around Pune. Start early at Pashan Lake, continue to Mulshi Dam, wind through Tamhini Ghat, catch the Andharban View Point and end the day at the stunning Pawna Lake. Perfect for photography and nature walks.',
 2585.00, 'INR', 1, 'AVAILABLE', true,
 'Pune',
 'Pune → Pashan Lake (6:30AM) → Mulshi Dam (8:30AM) → Tamhini Ghat (10:30AM) → Andharban Point (12PM) → Pawna Lake (2:30PM) → Pune (5:30PM)',
 180,
 'Pashan Lake,Tamhini Ghat,Andharban View Point,Pawna Lake',
 'FOUR_SEATER', 180.0,
 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 3: Lonavala Weekend Escape
(gen_random_uuid(),
 'lonavala-weekend-escape',
 'Lonavala Weekend Escape',
 'Lonavala & Khandala',
 'Weekend',
 'Two-day escape to Lonavala and Khandala with Tiger Point, Bhushi Dam, Rajmachi Fort base and Pawna Lake night camping.',
 'A premium 2-day weekend getaway to the Western Ghats. Day 1 covers sunrise at Tiger Point, Bhushi Dam, Lonavala Market lunch, Khandala Ghat sunset and Pawna Lake night camping with BBQ. Day 2 starts with sunrise boating on Pawna Lake followed by Rajmachi Fort base trek before returning to Pune.',
 5720.00, 'INR', 2, 'AVAILABLE', true,
 'Pune',
 'Day1: Pune → Tiger Point (sunrise) → Bhushi Dam → Lonavala Market (lunch) → Khandala Ghat (sunset) → Pawna Lake (night camping/BBQ). Day2: Pawna Lake (sunrise boating) → Rajmachi Fort Base (trek/view) → Pune (afternoon drop)',
 220,
 'Tiger Point,Bhushi Dam,Lonavala Market,Khandala Ghat,Rajmachi Fort Base,Pawna Lake Camping',
 'SIX_SEATER', 220.0,
 'https://images.unsplash.com/photo-1596484552834-6a58f850e0a1?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 4: Ashtavinayak Circuit (Pune Side)
(gen_random_uuid(),
 'ashtavinayak-circuit-pune',
 'Ashtavinayak Circuit (Pune Side)',
 'Jejuri Ganpati',
 'Spiritual',
 'Spiritual day circuit covering Jejuri, Ranjangaon Ganpati, Ozar Ganpati, Alandi and Dehu.',
 'A devotional day circuit covering key Ashtavinayak temples on the Pune side. Includes Khandoba temple at Jejuri, Ranjangaon Mahaganapati, Ozar Vigneshwara, and the sacred pilgrim towns of Alandi (Sant Dnyaneshwar) and Dehu (Sant Tukaram).',
 3245.00, 'INR', 1, 'AVAILABLE', false,
 'Pune',
 'Pune → Jejuri → Ranjangaon → Ozar → Alandi → Dehu → Pune',
 240,
 'Ranjangaon Ganpati,Ozar Ganpati,Alandi,Dehu',
 'FOUR_SEATER', 240.0,
 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 5: Nashik Spiritual Circuit
(gen_random_uuid(),
 'nashik-spiritual-circuit',
 'Nashik Spiritual Circuit',
 'Trimbakeshwar Temple',
 'Spiritual',
 'Full-day spiritual tour from Pune to Trimbakeshwar, Kalaram Temple, Sita Gufa, Kapaleshwar, Muktidham and Someshwar.',
 'A complete Nashik spiritual circuit covering the sacred Trimbakeshwar Jyotirlinga and all key Panchavati temples. Includes early morning Trimbakeshwar darshan, Kalaram Temple, Sita Gufa cave, Kapaleshwar Temple, Muktidham and Someshwar before returning to Pune.',
 4345.00, 'INR', 1, 'AVAILABLE', false,
 'Nashik',
 'Pune → Trimbakeshwar (early morning) → Kalaram Temple → Sita Gufa → Kapaleshwar → Muktidham → Someshwar → Pune',
 460,
 'Kalaram Temple (Panchavati),Sita Gufa,Kapaleshwar Temple,Muktidham Temple,Someshwar Temple',
 'FOUR_SEATER', 460.0,
 'https://images.unsplash.com/photo-1609766857584-d6d44d4c8ff5?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 6: Nashik Wine & Nature Weekend
(gen_random_uuid(),
 'nashik-wine-nature-weekend',
 'Nashik Wine & Nature Weekend',
 'Sula Vineyards',
 'Wine & Nature',
 'Two-day Nashik experience covering Igatpuri, Pandav Leni Caves, Sula Vineyards, York Winery, Gangapur Dam and Anjneri Hill.',
 'A premium 2-day Nashik wine and nature weekend. Day 1 covers Igatpuri breakfast stop, ancient Pandav Leni caves, Sula Vineyards wine tasting and lunch, and York Winery sunset session with Nashik overnight. Day 2 explores Gangapur Dam and the Anjneri Hill trek before returning to Pune via Igatpuri.',
 8085.00, 'INR', 2, 'AVAILABLE', false,
 'Nashik',
 'Day1: Pune → Igatpuri (breakfast) → Pandav Leni (caves) → Sula Vineyards (wine tasting+lunch) → York Winery (sunset tasting) → Nashik stay. Day2: Gangapur Dam (morning) → Anjneri Hill (trek/view) → Pune (afternoon via Igatpuri)',
 500,
 'Igatpuri,Pandav Leni Caves,York Winery,Gangapur Dam,Anjneri Hill',
 'SIX_SEATER', 500.0,
 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 7: Nashik Express (Spiritual + Wine)
(gen_random_uuid(),
 'nashik-express-spiritual-wine',
 'Nashik Express (Spiritual + Wine)',
 'Trimbakeshwar + Sula Vineyards',
 'Mixed',
 'One-day Nashik express combining Trimbakeshwar darshan, Sula Vineyards wine tasting, Pandav Leni and Gangapur Dam sunset.',
 'The best of Nashik in a single day. Early morning Trimbakeshwar Jyotirlinga darshan, wine tasting and lunch at Sula Vineyards, ancient Pandav Leni caves, and a scenic Gangapur Dam sunset before returning to Pune.',
 4235.00, 'INR', 1, 'AVAILABLE', false,
 'Nashik',
 'Pune → Trimbakeshwar (early morning darshan) → Sula Vineyards (wine+lunch) → Pandav Leni → Gangapur Dam (sunset) → Pune',
 450,
 'Pandav Leni,Gangapur Dam',
 'FOUR_SEATER', 450.0,
 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 8: Shirdi Sai Express
(gen_random_uuid(),
 'shirdi-sai-express',
 'Shirdi Sai Express',
 'Shirdi Sai Baba Temple',
 'Spiritual',
 'Full-day Shirdi pilgrimage covering Shani Shingnapur, Sai Baba Temple, Dwarkamai, Chavadi, Gurusthan and Lendi Baug.',
 'A complete Shirdi Sai pilgrimage covering all key sacred sites in a single day. Includes morning visit to Shani Shingnapur, main Sai Baba Temple darshan, Dwarkamai, Chavadi, Gurusthan and Lendi Baug garden before returning to Pune.',
 4125.00, 'INR', 1, 'AVAILABLE', false,
 'Shirdi',
 'Pune → Shani Shingnapur (morning) → Shirdi Temple (main darshan) → Dwarkamai → Chavadi → Gurusthan → Lendi Baug → Pune',
 400,
 'Shani Shingnapur,Dwarkamai,Chavadi,Gurusthan,Lendi Baug',
 'FOUR_SEATER', 400.0,
 'https://images.unsplash.com/photo-1609766857584-d6d44d4c8ff5?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 9: Shirdi + Ellora Heritage Weekend
(gen_random_uuid(),
 'shirdi-ellora-heritage-weekend',
 'Shirdi + Ellora Heritage Weekend',
 'Shirdi + Ellora Caves',
 'Spiritual + Heritage',
 'Two-day pilgrimage and heritage tour covering all Shirdi temple sites, Ellora Caves UNESCO site, Grishneshwar and Daulatabad Fort.',
 'A 2-day spiritual and heritage journey. Day 1 covers the complete Shirdi pilgrimage — Shani Shingnapur, Sai Baba Temple, Dwarkamai, Chavadi, Gurusthan and Lendi Baug — with Shirdi overnight. Day 2 visits Grishneshwar Jyotirlinga, UNESCO Ellora Caves and Daulatabad Fort before returning to Pune.',
 8415.00, 'INR', 2, 'AVAILABLE', false,
 'Shirdi',
 'Day1: Pune → Shani Shingnapur → Shirdi (Temple, Dwarkamai, Chavadi, Gurusthan, Lendi Baug) → Shirdi stay. Day2: Grishneshwar Temple (morning) → Ellora Caves (UNESCO tour) → Daulatabad Fort → Pune (evening)',
 550,
 'Shani Shingnapur,Grishneshwar Temple,Daulatabad Fort',
 'SIX_SEATER', 550.0,
 'https://images.unsplash.com/photo-1549429188-fb2cebba83bd?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now()),

-- Route 10: Grand Spiritual Triangle
(gen_random_uuid(),
 'grand-spiritual-triangle',
 'Grand Spiritual Triangle',
 'Nashik + Shirdi Complete',
 'Grand Spiritual',
 'Three-day grand spiritual triangle covering complete Nashik temples, Sula Vineyards, full Shirdi pilgrimage, Ellora Caves and Daulatabad Fort.',
 'The ultimate Maharashtra spiritual journey across 3 days. Day 1: Nashik — Igatpuri, Pandav Leni, Trimbakeshwar, all Panchavati temples and Sula Vineyards. Day 2: Full Shirdi pilgrimage at all sacred sites. Day 3: Shani Shingnapur, Grishneshwar, UNESCO Ellora Caves and Daulatabad Fort before returning to Pune.',
 13145.00, 'INR', 3, 'AVAILABLE', false,
 'Multi-Region',
 'Day1: Pune → Igatpuri (breakfast) → Pandav Leni → Trimbakeshwar → Panchavati Temples → Sula Vineyards (sunset) → Nashik stay. Day2: Nashik → Shirdi (full day all temple sites) → Shirdi stay. Day3: Shirdi → Shani Shingnapur → Grishneshwar → Ellora Caves → Daulatabad Fort → Pune (evening drop)',
 850,
 'Igatpuri,Pandav Leni,Trimbakeshwar,Panchavati Temples (Kalaram/Sita Gufa/Kapaleshwar),Sula Vineyards,Shirdi All Sites,Shani Shingnapur,Ellora Caves,Grishneshwar Temple,Daulatabad Fort',
 'SIX_SEATER', 850.0,
 'https://images.unsplash.com/photo-1549429188-fb2cebba83bd?auto=format&fit=crop&w=1200&q=80',
 'ALWAYS', now(), now());
